#!/bin/bash
# QUICK TEST GUIDE - Run in order

echo "🧪 RECIPE SHARING APP - QUICK TEST GUIDE"
echo "==============================================="
echo ""
echo "✅ Backend Status"
echo "   • API: http://localhost:4000/health"
echo "   • DB: http://localhost:4000/health/db"
echo ""
echo "✅ Frontend: http://localhost:5174"
echo ""
echo "==============================================="
echo ""
echo "📋 MANUAL TESTING (Do this in browser):"
echo ""
echo "1️⃣  HOME PAGE"
echo "   □ Check featured recipe section has gap from slider"
echo "   □ Check featured description doesn't overlap text"
echo "   □ Check recipe cards display properly"
echo "   □ Hover on cards - smooth animation"
echo ""
echo "2️⃣  AUTHENTICATION"
echo "   □ Click 'Sign Up' → Create new account"
echo "   □ Success toast shows → Redirects home"
echo "   □ Try login → Works with credentials"
echo "   □ Try logout → Session cleared"
echo ""
echo "3️⃣  LIKE/SAVE (CRITICAL TEST)"
echo "   □ Click like button on any recipe"
echo "   □ See success toast (not error)"
echo "   □ Button changes to 'liked' state"
echo "   □ Click save button"
echo "   □ See success toast (not '401 unauthorized')"
echo "   □ Refresh page → Like/save state persists"
echo ""
echo "4️⃣  RECIPES PAGE"
echo "   □ Type in search box → Results filter"
echo "   □ Click category pill → Filters update"
echo "   □ Click sort icon → Modal opens in center"
echo "   □ Select sort option → Results reorder"
echo "   □ Read descriptions → No overlapping text"
echo ""
echo "5️⃣  MOBILE (Press F12 → Toggle Device)"
echo "   □ 480px width: Buttons clickable (44px min)"
echo "   □ 375px width: Extra small text readable"
echo "   □ Sort modal centered (not at bottom)"
echo "   □ Navbar filter inline with menu"
echo ""
echo "6️⃣  DARK MODE"
echo "   □ Click theme toggle button"
echo "   □ Colors change to dark"
echo "   □ Text still readable"
echo "   □ Toggle back - light mode returns"
echo ""
echo "==============================================="
echo ""
echo "✅ DEVELOPER CHECKS"
echo "   □ F12 → Console: 0 errors (warnings OK)"
echo "   □ F12 → Network: All requests 200/201"
echo "   □ All buttons clickable"
echo "   □ No dead links"
echo ""
echo "==============================================="
echo ""
echo "🚀 IF ALL TESTS PASS:"
echo "   git add ."
echo "   git commit -m 'Fix: like/save, spacing, error handling'"
echo "   git push origin main"
echo ""
echo "⚠️  IF ANY TEST FAILS:"
echo "   1. Note the issue"
echo "   2. Check TEST_RESULTS.md for details"
echo "   3. Report the problem"
echo ""
echo "==============================================="
echo "Happy Testing! 🎉"
